# Generated by Django 5.1.15 on 2026-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('discount_flat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
        ),
    ]
